# AI Configuration
openai:
  api_key: "your-openai-api-key-here"
  model: "gpt-4"
  temperature: 0.3
  max_tokens: 2000
  max_retries: 3
  use_azure: false
  azure_endpoint: ""  # Optional: "https://your-resource.openai.azure.com/"
  azure_version: ""  # Optional: "2023-12-01-preview"
  langsmith_project: "powerbi-automation"  # Optional: for LangSmith tracing
  langsmith_endpoint: "https://api.smith.langchain.com"  # Optional: "https://api.smith.langchain.com"

# Microsoft Fabric Configuration
fabric:
  tenant_id: "your-tenant-id-here"
  client_id: "your-client-id-here"
  client_secret: "your-client-secret-here"
  workspace_id: "your-workspace-id-here"
  pipeline_id: "your-pipeline-id-here"  # Optional
  capacity_id: "your-capacity-id-here"  # Optional
  api_endpoint: "https://api.fabric.microsoft.com/v1"

# Data Sources Configuration
data_sources:
  sales_data:
    type: "sql_server"
    server: "your-server-name.database.windows.net"
    database: "your-database-name"
    username: "your-username"
    password: "your-password"
    driver: "ODBC Driver 17 for SQL Server"
    connection_string: ""  # Optional alternative to individual params
    connection_pool_size: 5
    connection_timeout: 30
  
  customer_data:
    type: "postgresql"
    host: "your-postgres-server"
    port: 5432
    database: "your-database"
    username: "your-username"
    password: "your-password"
    schema: "public"
    connection_pool_size: 5
    connection_timeout: 30
  
  product_catalog:
    type: "csv"
    file_path: "/path/to/your/product_catalog.csv"
  
  financial_data:
    type: "excel"
    file_path: "/path/to/your/financial_data.xlsx"
  
  api_data:
    type: "api"
    url: "https://api.example.com/data"
    headers:
      Authorization: "Bearer your-api-token"
    params:
      limit: 100
    paginate: false
  
  bigquery_data:
    type: "bigquery"
    project_id: "your-gcp-project-id"
    credentials_path: "/path/to/your/service-account-key.json"
  
  salesforce_data:
    type: "salesforce"
    username: "your-salesforce-username"
    password: "your-salesforce-password"
    security_token: "your-security-token"
    sandbox: false
  
  s3_data:
    type: "s3"
    access_key_id: "your-aws-access-key"
    secret_access_key: "your-aws-secret-key"
    region: "us-east-1"
    bucket_name: "your-bucket-name"
    prefix: "data/"
  
  onelake_data:
    type: "onelake"
    workspace_id: "your-workspace-id"
  
  # Additional data source types from LangChain implementation
  mysql_data:
    type: "mysql"
    host: "your-mysql-server"
    port: 3306
    database: "your-database"
    username: "your-username"
    password: "your-password"
  
  oracle_data:
    type: "oracle"
    host: "your-oracle-server"
    port: 1521
    service_name: "your-service-name"
    username: "your-username"
    password: "your-password"
  
  snowflake_data:
    type: "snowflake"
    account: "your-account"
    warehouse: "COMPUTE_WH"
    database: "your-database"
    schema: "your-schema"
    username: "your-username"
    password: "your-password"
  
  synapse_data:
    type: "synapse"
    server: "your-synapse-server.sql.azuresynapse.net"
    database: "your-database"
    username: "your-username"
    password: "your-password"

# Streaming Configuration
streaming:
  enabled: true
  kafka_bootstrap_servers: "kafka-server1:9092,kafka-server2:9092"
  kafka_topic: "powerbi-data-stream"
  event_hub_connection_string: "Endpoint=sb://your-namespace.servicebus.windows.net/;SharedAccessKeyName=your-policy;SharedAccessKey=your-key;EntityPath=your-eventhub"
  event_hub_name: "powerbi-events"
  consumer_group: "$Default"
  checkpoint_interval: 30
  batch_size: 100

# Copilot Configuration
copilot:
  enabled: true
  write_back_enabled: true
  data_agents_enabled: true
  grounding_context: 
    - "Sales data includes daily transactions from all regions"
    - "Customer data contains demographic and purchase history"
    - "Financial data is updated quarterly"
  terminology:
    "Revenue": "Total income from sales before deductions"
    "Churn Rate": "Percentage of customers who discontinued service"
  api_key: "your-copilot-api-key"

# UI Configuration
ui:
  low_code_enabled: true
  interactive_dashboards: true
  mobile_responsive: true
  theme: "standard"
  color_palette: ["#01B8AA", "#374649", "#FD625E", "#F2C80F", "#4BC0C0"]
  font_family: "Segoe UI"

# Advanced Analytics Configuration
advanced_analytics:
  predictive_modeling: true
  natural_language_querying: true
  automated_insights: true
  model_path: "/models"
  confidence_threshold: 0.7

# Data Quality Configuration
data_quality:
  enabled: true
  max_null_percentage: 30.0
  max_duplicate_percentage: 10.0
  check_outliers: true
  outlier_method: "zscore"  # Options: zscore, iqr
  outlier_threshold: 3.0
  check_data_types: true
  check_value_ranges: true
  custom_rules:
    - type: "column_pattern"
      pattern: "^[A-Za-z0-9_]+$"
      columns: ["product_id", "customer_id"]
      severity: "warning"

# Security Configuration
security:
  conditional_access: true
  mfa_required: true
  device_compliance_required: true
  ip_restrictions: []
  encryption_key: "your-encryption-key-here"  # Optional: for AES encryption
  api_key_rotation_days: 90

# Compliance Configuration
compliance:
  data_classification: "Confidential"
  retention_policy: "7_years"
  audit_logging: true
  standards: ["GDPR", "SOX", "HIPAA"]

# Deployment Configuration
deployment:
  environment: "production"
  pipeline_stages: ["dev", "test", "prod"]
  auto_deployment: true
  approval_required: false

# Monitoring Configuration
monitoring:
  application_insights: "your-application-insights-connection-string"
  log_analytics_workspace: "your-log-analytics-workspace-id"
  prometheus_endpoint: "http://prometheus:9090"
  redis_url: "redis://localhost:6379"
  circuit_breaker_timeout: 60  # seconds
  rate_limit_requests: 100
  rate_limit_period: 60  # seconds
  enable_advanced_monitoring: true
  performance_benchmarking: true
  data_lineage_tracking: true

# Visualization Configuration
visualization:
  theme: "standard"
  color_palette: ["#01B8AA", "#374649", "#FD625E", "#F2C80F", "#4BC0C0"]
  font_family: "Segoe UI"
  default_visualization_types: ["column", "line", "pie", "card", "table"]
  enable_custom_visuals: true

# Scaling Configuration
scaling:
  enabled: true
  min_workers: 2
  max_workers: 10
  scale_up_threshold: 0.7  # 70% utilization
  scale_down_threshold: 0.3  # 30% utilization
  cooldown_period: 300  # seconds
  distributed_processing: true
  kubernetes_enabled: true
  load_balancing: true
  resource_optimization: true
  auto_scaling:
    enabled: true
    min_capacity: "F2"
    max_capacity: "F64"
    scale_triggers:
      cpu_threshold: 80
      memory_threshold: 85
      concurrent_users: 1000
  load_balancing:
    enabled: true
    strategy: "round_robin"
    health_check_interval: 30
  caching:
    redis_cluster:
      enabled: true
      nodes: 3
      memory_per_node: "8GB"
  performance_optimization:
    query_timeout: 300
    max_concurrent_queries: 50
    incremental_refresh: true

# API Configuration
api:
  enabled: true
  host: "0.0.0.0"
  port: 8000
  cors_origins: ["*"]
  docs_url: "/docs"
  openapi_url: "/openapi.json"

# Multi-Geo Configuration
multi_geo_config:
  home_region: "West Europe"
  multi_geo_capacities: []
  data_residency_compliance: "GDPR"

# Integration Configuration
integrations:
  azure_devops_project: "https://dev.azure.com/your-org/your-project"
  teams_webhook: "https://outlook.office.com/webhook/your-webhook-url"
  key_vault_url: "https://your-key-vault-name.vault.azure.net/"

# General Configuration
max_workers: 4
data_chunk_size: 10000
max_sql_generation_try: 3
max_python_script_check: 3
sandbox_path: "/tmp/sandbox"
enable_fabric_deployment: true
enable_langsmith: true
enable_real_time_refresh: true